### ISSUE TITLE
Invalid CSS after "$center-headings: "

### ISSUE THREAD

**Issue by TiTi** [octopress/genesis-theme#12]
Hi,

I'm trying to use the genesis-theme for Octopress 3.0 on windows, but it doesn't build out of the box because of a SASS / variable issue :
```
C:\Users\TiTi\Desktop\octo3>jekyll build
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: C:/Users/TiTi/Desktop/octo4/_config.yml
            Source: C:/Users/TiTi/Desktop/octo4
       Destination: C:/Users/TiTi/Desktop/octo4/_site
      Generating...
jekyll 2.5.3 | Error:  Invalid CSS after "$center-headings: ": expected expression (e.g. 1px, bold), was ";"

C:\Users\TiTi\Desktop\octo3>
```

Note: I had to reference `octopress-genesis` rather than `octopress-genesis-theme` to bypass a first error, see #9 :
```
gems:
  - octopress-genesis
```

I tried to `octopress ink copy theme` and edit files to go further.
I've edited `_plugins\theme\stylesheets\index.scss` to force :

  $center-headings: true;

(despite the fact it is already setted to true in theme\config.yml)

And yep that's it, `jekyll build` is now working correctly.
So I guess the variable `{{ theme.center-headings }}` isn't available for some reason...

**Comment by fehwalker** [comment]
FWIW, I get this same thing on FreeBSD, so it's not a Windows thing.

octopress-genesis-theme (0.0.3)

> bryanf@testbed:~/dev/blog % jekyll build
> Configuration file: /export/storage/dev/blog/_config.yml
>             Source: /export/storage/dev/blog
>        Destination: /export/storage/dev/blog/_site
>       Generating...
> jekyll 2.5.3 | Error:  Invalid CSS after "$center-headings: ": expected expression (e.g. 1px, bold), was ";"
> bryanf@testbed:~/dev/blog %

Maybe I'll look at the source tomorrow...

**Comment by fehwalker** [comment]
Interestingly on the master branch this setting is now hardcoded to false, but in the 0.0.3 released gem it's still variable using Liquid (and broken because not initialized by default).

I have a patch that allows it to still be variable using Liquid templating logic, but defaulting to false as in master.

**Comment by change2hao** [comment]
I came across the same error on Yosemite

**Comment by imathis** [comment]
This should be solved in the latest release.
