### ISSUE TITLE
genesis-theme being overwritten by jekyll default theme

### ISSUE THREAD

**Issue by oflannabhra** [octopress/genesis-theme#18]
Not exactly sure how to troubleshoot this, but it looks like my configuration for the `genesis-theme` might not be set up right. Every page in my site is using the default jekyll theme [jekyll-new](https://github.com/jglovier/jekyll-new) except for the Archive page. Every page is including `genesis-theme` header, just not the proper assets or layout. Also, the `_plugins/theme/config.yml` title and subtitle are not being picked up.

I installed the genesis-theme gem after generating the jekyll site with `octopress new`, which might have created this issue?

**Comment by imathis** [comment]
The genesis theme is definitely in alpha, so I wouldn't build a public site on it right now. I still have things to work on. But aside from that, have you updated your posts and pages with `layout: theme:post` or `layout: theme:page`?

**Comment by oflannabhra** [comment]
I was using the following
```
layout: post
theme: post
```
which now is pretty obvious.
