### ISSUE TITLE
Liquid Exception: no implicit conversion of String into Hash in _layouts/post.html

### ISSUE THREAD

**Issue by fred-o** [octopress/genesis-theme#26]
It seems the line

      {% include theme:post_meta.html | join_lines %}

in layouts/post.html is causing problems. When I run 'jekyll server' I get the error 'Liquid Exception: no implicit conversion of String into Hash in _layouts/post.html'. If I remove the line everything works fine.

These are my gems:

  * autoprefixer-rails (2.2.0.20140804)
  * blankslate (2.1.2.4)
  * bundler (1.9.1)
  * celluloid (0.16.0)
  * classifier-reborn (2.0.3)
  * coffee-script (2.3.0)
  * coffee-script-source (1.9.1)
  * colorator (0.1)
  * execjs (2.4.0)
  * fast-stemmer (1.0.2)
  * ffi (1.9.8)
  * hitimes (1.2.2)
  * jekyll (2.5.3)
  * jekyll-coffeescript (1.0.1)
  * jekyll-gist (1.2.1)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (1.3.0)
  * jekyll-sitemap (0.8.1)
  * jekyll-watch (1.2.1)
  * json (1.8.2)
  * kramdown (1.6.0)
  * liquid (2.6.2)
  * listen (2.10.0)
  * mercenary (0.3.5)
  * octopress (3.0.0.rc.35)
  * octopress-asset-pipeline (2.0.3)
  * octopress-assign-tag (1.0.2)
  * octopress-autoprefixer (1.0.0)
  * octopress-categories (0.0.1)
  * octopress-code-highlighter (4.2.3)
  * octopress-codeblock (1.0.5)
  * octopress-codefence (1.6.0)
  * octopress-comment-tag (1.0.1)
  * octopress-content-for (1.0.4)
  * octopress-date-format (3.0.2)
  * octopress-deploy (1.2.0)
  * octopress-escape-code (2.0.6)
  * octopress-feeds (2.0.3)
  * octopress-filter-tag (1.0.1)
  * octopress-filters (1.3.3)
  * octopress-genesis-theme (0.0.8)
  * octopress-hooks (2.6.0)
  * octopress-image-tag (1.1.0)
  * octopress-include-tag (1.0.3)
  * octopress-ink (1.0.0.rc.58)
  * octopress-linkblog (2.0.1)
  * octopress-paginate (1.1.2)
  * octopress-pullquote-tag (1.0.1)
  * octopress-render-tag (1.0.6)
  * octopress-return-tag (1.0.1)
  * octopress-social (1.4.1)
  * octopress-solarized (1.0.3)
  * octopress-tag-helpers (1.0.4)
  * octopress-wrap-tag (1.0.3)
  * parslet (1.5.0)
  * posix-spawn (0.3.10)
  * pygments.rb (0.6.3)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * redcarpet (3.2.2)
  * rubypants-unicode (0.2.5)
  * safe_yaml (1.0.4)
  * sass (3.4.13)
  * timers (4.0.1)
  * titlecase (0.1.1)
  * toml (0.1.2)
  * uglifier (2.7.1)
  * yajl-ruby (1.2.1)

**Comment by fred-o** [comment]
I traced this down to the email sharing link; if there is no email addy configured for the octopress/social plugin I get this error. Workaround: configure an email address or disable email sharing.

**Comment by imathis** [comment]
Thanks! I'll get a fix out soon.

**Comment by imathis** [comment]
Ok, looking at this further it seems this is a configuration collision. You probably have `email: you@somewhere.com` defined in your Jekyll configuration. The Octopress Social plugin expects [email to be a hash](https://github.com/octopress/social#email-sharing) of options. If you update your configuration to match that it should work, but I can see how other plugins may expect email not to be a hash. I'll work on a solution that avoids collision.

**Comment by imathis** [comment]
I've just released a new version of octopress-social. Update that gem and you should be good to go. Thanks for helping me find this bug :)

**Comment by fred-o** [comment]
Thanks for your hard work, btw. I love octopress 3 :)

**Comment by imathis** [comment]
Awesome. I'm glad to hear it!
