### ISSUE TITLE
No css for code highlighting

### ISSUE THREAD

**Issue by awatts** [octopress/genesis-theme#29]
When using octopress-codefence, octopress-codeblock, plain old Jekyll {% hightlight %} tags, etc. with the theme, the code gets the appropriate HTML tags and CSS classes, but no CSS gets included to style it.
If I switch from "layout: theme:post" to "layout: default", the syntax highlighting comes back. I will grant that I might be doing something wrong, but if that's the case then my failure could hopefully inform documentation needs.

**Comment by imathis** [comment]
Sorry about this. I'll see what's going on.

**Comment by imathis** [comment]
@awatts Ah, I think you probably want to install [octopress-solarized](https://github.com/octopress/solarized). If you still have trouble let me know.

**Comment by awatts** [comment]
That worked! Thanks!
