### ISSUE TITLE
overriding scss files

### ISSUE THREAD

**Issue by tjaartvdwalt** [octopress/genesis-theme#42]
Hi,

First off, thanks for a great project. Octopress really simplify deploying my Jekyll blogs.

I have a question on overriding/adding custom stylesheets to the *genesis-theme*. In the `README` you mention that this is possible:

> You can also easily overwrite stylesheets, layouts, partials and basically everything about this plugin by adding a copy of that file in the `_plugins/theme` directory. More on that later.

How does this work exactly? 
I want to override `index.scss`, and I tried to place my new file at `_plugins/theme/index.scss`  and `_plugins/theme/assets/stylesheets/index.scss` but it does not seem to have any effect.

**Comment by iratebeagle** [comment]
_plugins/theme/stylesheets works, although I've had issues with overrides breaking the theme, so if anyone has info on that I'd be interested. I was trying to add image left/center/right styling and the theme just completely broke when I added the image formatting from the old octopress image tag.

**Comment by fraank** [comment]
Is it possible that overwriting settings from "_config.yml" with "_plugins/theme/config.yml" is also broken?

**Comment by tjaartvdwalt** [comment]
@fraank: I found that my changes to `_plugins/theme/config.yml` does not take effect if I simply have `jekyll serve` running. I can force it by either killing and restarting `jekyll serve`, or by running `jekyll build`.

Mabye that the same for you?

**Comment by tjaartvdwalt** [comment]
@iratebeagle: Thanks for answering my question.
It seems the correct place to override scss files is

`_plugins/theme/stylesheets`

**Comment by fraank** [comment]
No, that doesn't solve my problem. See this issue: https://github.com/octopress/genesis-theme/issues/44

**Comment by tjaartvdwalt** [comment]
@fraank: Oh I misunderstood exactly what you meant. Unfortunately my site is only in English, so I cannot be of help.
