### ISSUE TITLE
It takes an eternity to resolve dependencies

### ISSUE THREAD

**Issue by pama** [octopress/genesis-theme#48]
I'm trying to bundle the following `Gemfile`:

```
gem 'jekyll'

group :jekyll_plugins do
  gem 'octopress', '~> 3.0'
  gem 'octopress-genesis-theme'
end
```

**Comment by tigefa4u** [comment]
try this

``` yaml
gem 'jekyll'

group :jekyll_plugins do
  gem 'octopress'
  gem 'octopress-genesis-theme'
end
```

remove `, '~> 3.0'` :+1:

**Comment by pama** [comment]
Same problem @tigefa4u ; latest version is 3.0.1 so it won't make a difference.

**Comment by bronislav** [comment]
@pama it's because gemspec doesn't specify versions and bundler found more than one way to resolve dependencies, I believe.
